#!name=信用卡 3D 驗證自動填寫修正
#!desc=修正信用卡 3D 驗證無法觸發 iOS 自動填寫功能

[Script]
[3D 驗證修正] NCCC = type=http-response, pattern=^https:\/\/webauthen\.nccc\.com\.tw\/acsn2_kernel\/2\/browser\/challenge-otp$,script-path=https://gnehs.github.io/surge-modules/scripts/nccc-3d.js, requires-body=true
[3D 驗證修正] 國泰 = type=http-response, pattern=^https:\/\/3ds\.cathaybk\.com\.tw\/(.*),script-path=https://gnehs.github.io/surge-modules/scripts/nccc-3d.js, requires-body=true

[MITM]
hostname = %APPEND% webauthen.nccc.com.tw, 3ds.cathaybk.com.tw
